### ISSUE TITLE
Shizuku cannot start on Android 7

### ISSUE THREAD

**Issue by Saud-97** [RikkaApps/Shizuku#218]
**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.6.2
- Mode: [adb, root] Both
- Android version: 7
- Device: (optional) Oneplus5

**Logs:**

Related **full logcat**.
```
2022-06-07 21:38:04.021 1826-2636/system_process I/ActivityManager: START u0 {cmp=moe.shizuku.privileged.api/moe.shizuku.manager.starter.StarterActivity (has extras)} from uid 11118 on display 0
2022-06-07 21:38:04.021 1826-2636/system_process D/ActivityManager: TopActivityInfo, pkgName: moe.shizuku.privileged.api activityName: moe.shizuku.manager.starter.StarterActivity callingPackage: moe.shizuku.privileged.api  
2022-06-07 21:38:04.022 1535-1633/? I/audio_hw_primary: choose pcmC0D0p for 0
2022-06-07 21:38:04.024 1826-2636/system_process D/ActivityManager: TopActivityInfo, pkgName: moe.shizuku.privileged.api activityName: moe.shizuku.privileged.api/moe.shizuku.manager.starter.StarterActivity callingPackage:   
2022-06-07 21:38:04.025 1826-2636/system_process D/WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
2022-06-07 21:38:04.040 11739-11739/? I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
2022-06-07 21:38:04.062 13662-13662/? D/Shizuku: applet shizuku_starter
2022-06-07 21:38:04.067 13662-13662/? D/Shizuku: start_server
2022-06-07 21:38:04.067 13663-13663/? D/Shizuku: child
2022-06-07 21:38:04.067 13663-13663/? D/Shizuku: exec app_process
2022-06-07 21:38:04.092 1535-1633/? D/AudioFlinger: mixer(0xe8a03e00) throttle end: throttle time(29)
2022-06-07 21:38:04.101 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.118 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.120 1826-1847/system_process V/WindowManager: isVisibleLw false for win : Window{b7c5ff0 u0 moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity}
2022-06-07 21:38:04.121 1826-2636/system_process D/InputMethodManagerService: packageName=moe.shizuku.privileged.api, activityName=moe.shizuku.manager.starter.StarterActivity
2022-06-07 21:38:04.121 1826-1847/system_process D/ActivityManager: windowsDrawnLocked: packageName = moe.shizuku.privileged.api, name = moe.shizuku.manager.starter.StarterActivity, mCallingPackage = com.android.packageinstaller
2022-06-07 21:38:04.122 1826-1847/system_process I/ActivityManager: Displayed moe.shizuku.privileged.api/moe.shizuku.manager.starter.StarterActivity: +97ms
2022-06-07 21:38:04.122 1826-2636/system_process D/InputMethodManagerService: ime_enabled = false is same as last value, no change
2022-06-07 21:38:04.124 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.140 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.144 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.149 11739-11758/? D/OpenGLRenderer: endAllActiveAnimators on 0x7ff2d1c6dc00 (RippleDrawable) with handle 0x7ff2d189b5c0
2022-06-07 21:38:04.152 11739-11758/? D/EGL_emulation: eglMakeCurrent: 0x7ff2e8283600: ver 3 1 (tinfo 0x7ff2e820c780)
2022-06-07 21:38:04.193 13663-13663/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2022-06-07 21:38:04.194 13663-13663/? D/AndroidRuntime: CheckJNI is OFF
2022-06-07 21:38:04.214 13663-13663/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2022-06-07 21:38:04.217 13663-13663/? W/art: Unexpected CPU variant for X86 using defaults: x86_64
2022-06-07 21:38:04.220 13663-13663/? W/: Failed to bind-mount /system/lib64/x86_64/cpuinfo as /proc/cpuinfo: No such file or directory
2022-06-07 21:38:04.220 13663-13663/? W/: Failed to bind-mount /system/lib64/x86_64/cpuinfo as /proc/cpuinfo: No such file or directory
2022-06-07 21:38:04.225 13663-13663/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2022-06-07 21:38:04.225 13663-13663/? E/android.os.Debug: failed to load memtrack module: -2
2022-06-07 21:38:04.226 13663-13663/? I/Radio-JNI: register_android_hardware_Radio DONE
2022-06-07 21:38:04.229 13663-13663/? D/AndroidRuntime: Calling main entry rikka.shizuku.server.ShizukuService
2022-06-07 21:38:04.230 13663-13663/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-06-07 21:38:04.231 13663-13663/? E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
    java.lang.UnsatisfiedLinkError: Couldn't find "/data/app/moe.shizuku.privileged.api-1/base.apk!/lib/x86_64/librish.so", no such file exists
        at java.lang.Runtime.load0(Runtime.java:914)
        at java.lang.System.load(System.java:1537)
        at rikka.rish.b.f(SourceFile:3)
        at rikka.rish.b.e(SourceFile:4)
        at rikka.shizuku.server.c.<init>(SourceFile:2)
        at rikka.shizuku.server.ShizukuService.<init>(SourceFile:1)
        at rikka.shizuku.server.ShizukuService.main(SourceFile:4)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:290)
2022-06-07 21:38:04.231 13663-13663/? I/Process: Sending signal. PID: 13663 SIG: 9
```

**Describe the bug:**

When starting shizuku using root I within app I get:
```
Starting with root...

info: start.sh begin
info: attempt to copy starter from /data/user_de/0/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
warn: can't read cgroup
info: starter begin
info: killing old process...
info: use apk path from argv
info: apk path is /data/app/moe.shizuku.privileged.api-1/base.apk
info: starting server...
info: shizuku_starter exit with 0

Waiting for service...
```

And when running using ADB I get:
```
127|OnePlus5:/ # sh /data/user/0/moe.shizuku.privileged.api/start.sh
sh: /data/user/0/moe.shizuku.privileged.api/start.sh: No such file or directory
ed/0/Android/data/moe.shizuku.privileged.api/start.sh                         <
info: start.sh begin
info: attempt to copy starter from /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
warn: can't read cgroup
avc:  denied  { call } for  scontext=u:r:untrusted_app:s0 tcontext=u:r:adbd:s0 tclass=binder permissive=1
avc:  denied  { transfer } for  scontext=u:r:untrusted_app:s0 tcontext=u:r:adbd:s0 tclass=binder permissive=1
info: starter begin
info: killing old process...
info: apk path is /data/app/moe.shizuku.privileged.api-1/base.apk
info: starting server...
info: shizuku_starter exit with 0
OnePlus5:/ #
OnePlus5:/ #
OnePlus5:/ #
```

**Additional context:**

I was not able to start shizuku at all. Logcat shows some helpful info on what has crashed and why.

**Comment by Saud-97** [comment]
Yes I am using BlueStacks 5.

Is there anyway to make it work? I have root access.
Thank you.

**Comment by RikkaW** [comment]
We don’t provide support since anything could happen on these weird emulators.
