### ISSUE TITLE
AndroidP 息屏状态错误

### ISSUE THREAD

**Issue by zxc111** [RikkaApps/Shizuku#22]
1. 无法在息屏状态开启 ADB，报错如下
```
sailfish:/ $ sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh                                                                                                                             
info: start.sh begin
info: starter begin
info: old shizuku_server found, killing
info: dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-27-v30.dex
info: process forked, pid=19315
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '07-23 12:14:12.000' -d
07-23 12:14:12.886 17572 17572 E AndroidRuntime: FATAL EXCEPTION: main
07-23 12:14:12.886 17572 17572 E AndroidRuntime: Process: moe.shizuku.privileged.api, PID: 17572
07-23 12:14:12.886 17572 17572 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=moe.shizuku.manager.service.action.AUTH cmp=moe.shizuku.privileged.api/moe.shizuku.manager.service.WorkService }: app is in background uid UidRecord{fda9a97 u0a220 TPSL bg:+4m3s845ms idle procs:1 seq(0,0,0)}
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3784)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=moe.shizuku.manager.service.action.AUTH cmp=moe.shizuku.privileged.api/moe.shizuku.manager.service.WorkService }: app is in background uid UidRecord{fda9a97 u0a220 TPSL bg:+4m3s845ms idle procs:1 seq(0,0,0)}
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1532)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at moe.shizuku.manager.service.WorkService.startAuth(Unknown Source:12)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at moe.shizuku.manager.MainActivity.check(Unknown Source:0)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at moe.shizuku.manager.MainActivity.onResume(Unknown Source:3)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7292)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
07-23 12:14:12.886 17572 17572 E AndroidRuntime: 	... 11 more
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '07-23 12:14:12.000' -d -s ShizukuServer ShizukuManager
07-23 12:14:12.746 19316 19316 W ShizukuServer: unsupported system (28) detected, some API may not work
07-23 12:14:12.812 19316 19316 I ShizukuServer: uid: 2000
07-23 12:14:12.812 19316 19316 I ShizukuServer: api version: 28
07-23 12:14:12.812 19316 19316 I ShizukuServer: device: sailfish
07-23 12:14:12.812 19316 19316 I ShizukuServer: start version: 30 token: 7a7afaa6-c29f-4144-af0a-0d370abe6bbb
07-23 12:14:12.855 19316 19316 I ShizukuServer: send token to manager app in user 0
--- shizuku end ---
info: shizuku_starter exit with 0
```

2. 亮屏状态成功开启 ADB 后，息屏重亮后服务失效

还是我使用姿势有误？

**Comment by haruue** [comment]
我的设备也是 Pixel ，Android 9.0 PPR1.180610.009

1. 在 **熄屏** 并且 **Activity 被杀掉（从最近使用中移除）** 时成功复现，但是实际上服务是起来了的，主界面显示 running, but no correct token received, tap to request token，再点一下就能请求到正确的 token 。
```
sailfish:/ $ sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh                                        
info: start.sh begin
info: starter begin
info: old shizuku_server found, killing
info: dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-27-v30.dex
info: process forked, pid=27189
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '08-17 14:37:25.000' -d
08-17 14:37:25.751 27201 27201 E AndroidRuntime: FATAL EXCEPTION: main
08-17 14:37:25.751 27201 27201 E AndroidRuntime: Process: moe.shizuku.privileged.api, PID: 27201
08-17 14:37:25.751 27201 27201 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.shizuku.privileged.api/moe.shizuku.manager.TokenReceiveActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=moe.shizuku.manager.service.action.AUTH cmp=moe.shizuku.privileged.api/moe.shizuku.manager.service.WorkService }: app is in background uid UidRecord{52e7ccc u0a147 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=moe.shizuku.manager.service.action.AUTH cmp=moe.shizuku.privileged.api/moe.shizuku.manager.service.WorkService }: app is in background uid UidRecord{52e7ccc u0a147 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1532)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at moe.shizuku.manager.service.WorkService.startAuth(Unknown Source:12)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at moe.shizuku.manager.TokenReceiveActivity.onCreate(Unknown Source:12)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
08-17 14:37:25.751 27201 27201 E AndroidRuntime: 	... 11 more
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '08-17 14:37:25.000' -d -s ShizukuServer ShizukuManager
08-17 14:37:25.454 27190 27190 W ShizukuServer: unsupported system (28) detected, some API may not work
08-17 14:37:25.520 27190 27190 I ShizukuServer: uid: 2000
08-17 14:37:25.520 27190 27190 I ShizukuServer: api version: 28
08-17 14:37:25.520 27190 27190 I ShizukuServer: device: sailfish
08-17 14:37:25.520 27190 27190 I ShizukuServer: start version: 30 token: d36bc74f-a687-475b-b572-fd39dd4bc77e
08-17 14:37:25.563 27190 27190 I ShizukuServer: send token to manager app in user 0
08-17 14:37:25.745 27201 27201 I ShizukuManager: token update: d36bc74f-a687-475b-b572-fd39dd4bc77e
--- shizuku end ---
info: shizuku_starter exit with 0
```

2. 无法复现，只有当关掉 adb 时服务才会失效。

**Comment by wx198592** [comment]
我也遇到了楼上的OnePlus 6 这个问题，如何解决啊

**Comment by wx198592** [comment]
在电源管理中，不去优化这个应用的包 就可以解决

**Comment by Slept-Warrior** [comment]
一加6换成7Pro了，实测楼上wx198592兄弟说的没错。

大概是一加后台策略太激进了
