### ISSUE TITLE
realme c35 - java.lang.NullPointerException

### ISSUE THREAD

**Issue by kvnzmd** [RikkaApps/Shizuku#251]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: v12.14.0 Latest
- Mode: wireless debugging
- Android version: 11
- Device: realme c35

**Logs:**

Starting with wireless adb...

java.lang.NullPointerException

![314674099_3457672274468331_2613264658319101603_n](https://user-images.githubusercontent.com/117642477/200292685-36b14fa1-15d7-4d31-bc5c-28d043d1cddd.jpg)

**Describe the bug:**

the process just stopped at "java.lang.NullPointerException"

**Additional context:**

did all the necessary steps found on the website

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/suites/9165314431/artifacts/426796536 Try again with build, it will show detailed log.

**Comment by kvnzmd** [comment]
here's the detailed log:

Starting with wireless adb...


java.lang.NullPointerException
	at rikka.shizuku.lb0.e(Unknown Source:5)
	at moe.shizuku.manager.starter.b$a.l(SourceFile:5)
	at rikka.shizuku.k7.n(SourceFile:4)
	at rikka.shizuku.bh.run(SourceFile:18)
	at rikka.shizuku.bt.run(SourceFile:2)
	at rikka.shizuku.nd0.run(SourceFile:1)
	at kotlinx.coroutines.scheduling.a.l(SourceFile:1)
	at kotlinx.coroutines.scheduling.a$c.d(SourceFile:4)
	at kotlinx.coroutines.scheduling.a$c.n(SourceFile:4)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)

**Comment by kvnzmd** [comment]
Initial message when I opened the app:

Cannot write files:

java.io.FileNotFoundException: /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at moe.shizuku.manager.starter.Starter.copyStarter(Starter.kt:90)
	at moe.shizuku.manager.starter.Starter.writeSdcardFiles(Starter.kt:41)
	at moe.shizuku.manager.home.HomeActivity$writeStarterFiles$1.invokeSuspend(HomeActivity.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7838)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 13 more

---------------------
After pairing and starting Shizuku:

Starting with wireless adb...


java.lang.NullPointerException
	at moe.shizuku.manager.starter.Starter.getSdcardCommand(Starter.kt:22)
	at moe.shizuku.manager.starter.ViewModel$startAdb$1.invokeSuspend(StarterActivity.kt:187)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

---------------------
I'm not using Xposed modules. Phone is not rooted as well.

**Comment by RikkaW** [comment]
Does `/storage/emulated/0/Android/data/moe.shizuku.privileged.api` exists? This folder should be created automatically.

**Comment by alihusam-1** [comment]
same here

**Comment by RyuzR** [comment]
<img width="720" height="1604" alt="Image" src="https://github.com/user-attachments/assets/cb976623-5c65-4164-960a-81cf4f65f3d0" />


Hello me pls
