### ISSUE TITLE
termux无法执行rish，已经将"PKG"改为"com.termux"

### ISSUE THREAD

**Issue by huajiworld** [RikkaApps/Shizuku#265]
Please report bugs of Shizuku itself.

**Requirements:**

- 

- [x] Shizuku version is up-to-date

- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

**Information:**

- Shizuku version:13.0.0.r944.5f5d313
- Mode: [adb, root]adb
- Android version:8.1.0
- Device: (optional)华为畅享九 EMUI8.2，未root

**Logs**:
java.lang.IllegalArgumentException: Calling application did not provide package name
        at android.os.Parcel.readException(Parcel.java:2020)
        at android.os.Parcel.readException(Parcel.java:1962)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:4522)
        at rikka.shizuku.shell.ShizukuShellLoader.requestForBinder(ShizukuShellLoader.java:72)
        at rikka.shizuku.shell.ShizukuShellLoader.main(ShizukuShellLoader.java:143)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:316)

**Describe the bug:**
用termux无法执行rish，已经把PKG改为“com.termux”

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/issues/262#issuecomment-1381592985

**Comment by RikkaW** [comment]
I just found that Android 8.1 cannot use `broadcastIntent` also. Use this build https://github.com/RikkaApps/Shizuku/actions/runs/3996080411

**Comment by huajiworld** [comment]
> https://github.com/RikkaApps/Shizuku/issues/262#issuecomment-1381592985

我用的就是action里最新的版本啊
13.0.0.r944.5f5d313

**Comment by RikkaW** [comment]
用上面那个回复的当下还没有构建好的那个（
