### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Thewisem** [RikkaApps/Shizuku#284]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.2.1
- Mode: [adb, root] Adb
- Android version: 7.1.1 Nougat
- Device: (optional) Samsung Galaxy Tab A SM P555

**Logs:**
FATAL EXCEPTION: main
Process: moe.shizuku.privileged.api, PID: 28402
java.lang.RuntimeException: Unable to destroy activity {moe.shizuku.privileged.api/moe.shizuku.manager.management.ApplicationManagementActivity}: java.lang.UnsupportedOperationException
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4697)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1720)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$CowIterator.remove(CopyOnWriteArrayList.java:814)
	at java.util.Collection.removeIf(Collection.java:402)
	at rikka.shizuku.t90.S(SourceFile)
	at moe.shizuku.manager.management.ApplicationManagementActivity.onDestroy(SourceFile:2)
	at android.app.Activity.performDestroy(Activity.java:7255)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4657)
	... 9 more

Related **full logcat**.

**Describe the bug:**

It keeps crashing when I click on the authotised applications
**Additional context:**

**Comment by RikkaW** [comment]
This build should have fixed your problem. Please have a try. https://github.com/RikkaApps/Shizuku/actions/runs/4646543816
