### ISSUE TITLE
Huawei-harmonyos2.0-The issue of shizuku's rish file not working properly in the terminal emulator

### ISSUE THREAD

**Issue by MCxlm1** [RikkaApps/Shizuku#309]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:13.3.0.r1003.d4b24b0
- Mode: [adb]
- Android version:9
- Device: (optional)

**Logs:**
--------- beginning of system
06-03 21:02:37.606 12863 12863 V ActivityThread: callActivityOnCreate
06-03 21:02:37.638 12863 12863 D ActivityThread: add activity client record, r= ActivityRecord{9622ba0 token=android.os.BinderProxy@87d9bd6 {moe.shizuku.privileged.api/moe.shizuku.manager.shell.ShellTutorialActivity}} token= android.os.BinderProxy@87d9bd6
--------- beginning of main
06-03 21:10:57.966 12863 12863 W System.err: android.os.DeadObjectException
06-03 21:10:57.966 12863 12863 W System.err: 	at android.os.BinderProxy.transactNative(Native Method)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.os.BinderProxy.transact(Binder.java:1154)
06-03 21:10:57.966 12863 12863 W System.err: 	at rikka.shizuku.uh0.a(SourceFile:73)
06-03 21:10:57.966 12863 12863 W System.err: 	at moe.shizuku.manager.receiver.ShizukuReceiver.onReceive(SourceFile:25)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4120)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.app.ActivityThread.access$2400(ActivityThread.java:278)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:112)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.os.Looper.loop(Looper.java:216)
06-03 21:10:57.966 12863 12863 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7779)
06-03 21:10:57.966 12863 12863 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 21:10:57.967 12863 12863 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
06-03 21:10:57.967 12863 12863 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
06-03 21:12:16.523 12863 12863 W System.err: android.os.DeadObjectException
06-03 21:12:16.524 12863 12863 W System.err: 	at android.os.BinderProxy.transactNative(Native Method)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.os.BinderProxy.transact(Binder.java:1154)
06-03 21:12:16.524 12863 12863 W System.err: 	at rikka.shizuku.uh0.a(SourceFile:73)
06-03 21:12:16.524 12863 12863 W System.err: 	at moe.shizuku.manager.receiver.ShizukuReceiver.onReceive(SourceFile:25)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4120)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.app.ActivityThread.access$2400(ActivityThread.java:278)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:112)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.os.Looper.loop(Looper.java:216)
06-03 21:12:16.524 12863 12863 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7779)
06-03 21:12:16.524 12863 12863 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 21:12:16.524 12863 12863 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
06-03 21:12:16.524 12863 12863 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)

**Describe the bug:**

Error logs when executing shizuku's rish file in the terminal emulator

**Additional context:**

Perhaps this is a bug that only exists with Android 9

**Comment by umarontop703-cloud** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by umarontop703-cloud** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
