### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder moe.shizuku.server.IShizukuService.asBinder()' on a null object reference

### ISSUE THREAD

**Issue by H4xX0r1337** [RikkaApps/Shizuku#32]
I just called my ShizukuService.transactRemote(data, reply, 0), and I got this message. Shizuku is running and I have got the permission. 

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: de.unknown.appmanager, PID: 30878
    java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder moe.shizuku.server.IShizukuService.asBinder()' on a null object reference
        at moe.shizuku.api.ShizukuService.transactRemote(ShizukuService.java:42)
        at de.unknown.appmanager.ShizukuApi.deletePackage(ShizukuApi.kt:26)
        at de.unknown.appmanager.appmanagers.ShizukuAppManager$uninstallPackage$1.run(ShizukuAppManager.kt:76)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by RikkaW** [comment]
Have you added BinderReceiveProvider to your AndroidManifest.xml?

**Comment by H4xX0r1337** [comment]
@RikkaW yes, i pasted it into my manifest.

**Comment by H4xX0r1337** [comment]
@RikkaW Is there anything else I could have missed? This is my manifest. https://pastebin.com/9XXGdqFz

**Comment by H4xX0r1337** [comment]
@RikkaW Sorry for all of those messages, but I forgot to tell you, that I'm, using AndroidX.

**Comment by H4xX0r1337** [comment]
Okay, I feel really dumb. All I had to do was to put `MultiProcessHelper.initialize(main)` after getting permission. It crashed again, because I used an Oreo API on Lollipop. I thought the crashes were the same and reverted, So it's working now.
