### ISSUE TITLE
Neither user 2000 nor current process has android.permission.MANAGE_USERS

### ISSUE THREAD

**Issue by rahaaatul** [RikkaApps/Shizuku#325]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: `13.5`
- Mode: `adb`
- Android version: `11`
- Device: `Vivo Y20 2021`

**Logs:**
```
java.lang.SecurityException: Neither user 2000 nor current process has android.permission.MANAGE_USERS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2079)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2107)
        at com.android.server.pm.PackageManagerService.setApplicationHiddenSettingAsUser(PackageManagerService.java:13965)
        at com.android.server.pm.PackageManagerShellCommand.runSetHiddenSetting(PackageManagerShellCommand.java:2230)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:258)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23570)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5035)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4697)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

**Describe the bug:** 
Whenever I try to hide an app via termux run in shizuku shell it give this error:

> Neither user 2000 nor current process has android.permission.MANAGE_USERS

But I can Disable and Suspend apps in shizuku shell.

**Additional context:**
I also tried with Hail, but it didn't hide or suspend the app. It was also in shizuku working mode, if I hid the app using device owner mode, it hid without issue.

**Comment by RikkaW** [comment]
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/PackageManagerService.java;l=12953

https://cs.android.com/android/_/android/platform/frameworks/base/+/f5cea03eb036c05cacc711ff90c97a48ffb2bc17

`pm hide` (`setApplicationHiddenSettingAsUser`) requires `android.permission.MANAGE_USERS`, this permission is removed for adb starting from Android 7.0, so adb no longer has permission to use `pm hide`. This is simply a system change, not related to Shizuku.

For "Device owner mode", it uses DevicePolicyManager API which has a different permission check route, so it can work.
