### ISSUE TITLE
Wireless debug stop working at android 14

### ISSUE THREAD

**Issue by kemko** [RikkaApps/Shizuku#333]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.3.0.r993.5392b9d
- Mode: adb
- Android version: Android 14 UPB5.230623.003
- Device: Google Pixel 7 Pro

**Logs:**

```
Starting with wireless adb...


javax.net.ssl.SSLProtocolException: Read error: ssl=0xb4000076ddfe60d8: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb40000760e0145c0:0x00000003)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
	at java.io.DataInputStream.readFully(DataInputStream.java:203)
	at rikka.shizuku.o2.e(SourceFile:22)
	at rikka.shizuku.o2.a(SourceFile:195)
	at moe.shizuku.manager.starter.b$a.k(SourceFile:42)
	at rikka.shizuku.t8.l(SourceFile:12)
	at rikka.shizuku.si.run(SourceFile:119)
	at rikka.shizuku.gw.run(SourceFile:13)
	at rikka.shizuku.ji0.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.a.l(SourceFile:1)
	at kotlinx.coroutines.scheduling.a$c.d(SourceFile:15)
	at kotlinx.coroutines.scheduling.a$c.n(SourceFile:29)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
```

**Describe the bug:**

Wireless debug doesn't working after updated device to Android 14

**Comment by RikkaW** [comment]
Try pairing again?

**Comment by kemko** [comment]
Hmm. I think I tried, but now repairing helps. Thank you very much!
