### ISSUE TITLE
 Optimized data directory . is not owned by the current user. Shared storage cannot protect your application from code injection attacks.

### ISSUE THREAD

**Issue by 993739033** [RikkaApps/Shizuku#385]
Please report bugs of Shizuku itself.

**Requirements:**

- [] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:13.5.2
- Mode: [adb]
- Android version:7.1
- Device: (optional)

**Logs:**

rk3288:/ $ cd /sdcard/szk
rk3288:/sdcard/szk $ ls -a
. .. rish rish_shizuku.dex
rk3288:/sdcard/szk $ sh rish
java.lang.IllegalArgumentException: Optimized data directory . is not owned by the current user. Shared storage cannot protect your application from code injection attacks.
        at dalvik.system.DexFile.<init>(DexFile.java:139)
        at dalvik.system.DexFile.loadDex(DexFile.java:219)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:362)
        at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
        at dalvik.system.DexPathList.<init>(DexPathList.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
        at a.b.run(SourceFile)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at rikka.shizuku.shell.ShizukuShellLoader.main(SourceFile:2)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
1|rk3288:/sdcard/szk $

Related **full logcat**.

**Describe the bug:**
i use term but command not working

**Additional context:**

**Comment by RikkaW** [comment]
Just don't put rish file in /sdcard ?
