### ISSUE TITLE
The problem of using the Shizuku

### ISSUE THREAD

**Issue by xiaoze1332** [RikkaApps/Shizuku#54]
Samsung note 9
magisk
MiPushFramework伪装小米

Shizuku 安装器错误:

设备: Xiaomi SM-N9600 | MIUI | Android 8.1.0 | Install Lion-Root 2.91

java.lang.RuntimeException: Command: pm install-write -S 2702065 93877727 0.apk
Exit code: -1
Out:

=============
Err:

<!> SAI ShizukuShell Java exception: java.lang.RuntimeException: java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
 at b.c.a.c.d.b.a(:9)
 at b.c.a.c.c.d.a(:26)
 at b.c.a.c.c.a.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
 at d.a.a.a.getOutputStream(Unknown Source:17)
 at b.c.a.c.d.b.a(:7)
 ... 5 more
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
 at android.os.BinderProxy.transactNative(Native Method)
 at android.os.BinderProxy.transact(Binder.java:777)
 at d.a.b.a$a$a.e(Unknown Source:17)
 at d.a.a.a.getOutputStream(Unknown Source:6)
 ... 6 more

 at b.c.a.c.c.d.a(:27)
 at b.c.a.c.c.a.run(Unknown Source:4)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)

**Comment by kinton** [comment]
Hello everyone and @RikkaW!
Have problems on meizu pro 6 (flyme 8, android 7.1). Data transfer enabled, payment protection (in security app, can't find in developer options) disabled.
Here end of the output:
![q](https://user-images.githubusercontent.com/14817153/77850160-4a808500-71d9-11ea-8555-3ed6150f9ddd.jpg)

**Comment by RikkaW** [comment]
@kinton Please provide the full log (`adb logcat > 1.txt` before excute start script). Also, please create a new issue for this.

**Comment by RikkaW** [comment]
Please try v3.6.0

**Comment by kinton** [comment]
Sorry, It was problem with google apps and I changed the rom. Hopes issue will help sb else

**Comment by spikespaz** [comment]
I have the same issue on MIUI and would like to know if anyone has done any investigation into the matter. I can't simply switch ROMs because unfortunately there are none available, so I'm stuck with this crap. Any help appreciated, thanks!
