### ISSUE TITLE
Android 11 adb 启动失败

### ISSUE THREAD

**Issue by 4ft35t** [RikkaApps/Shizuku#55]
Pixel2 rpp1.200123.016
shizuku 3.5.0.r323.f399ca4

```log
info: start.sh begin
info: source dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-v6.dex
info: dex path is /data/local/tmp/shizuku/server-v6.dex
info: starter begin
info: killing old process...
info: killed 7259 (shizuku_server)
info: starting server v3...
info: process forked, pid=16089
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '02-21 11:52:44.000' -d
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '02-21 11:52:44.000' -d -s ShizukuServer ShizukuServerV3 ShizukuManager
--------- beginning of main
02-21 11:52:45.916 16090 16090 I ShizukuServerV3: server v3
02-21 11:52:45.916 16090 16090 I ShizukuServerV3: using token from arg
02-21 11:52:46.051 16090 16103 D ShizukuServerV3: onUidActive: uid=10196
02-21 11:52:46.052 16090 16103 D ShizukuServerV3: onActive: uid=10196, packages=rikka.appops
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: failed send binder to user app rikka.appops in user 0
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: java.lang.NoSuchMethodError: android.content.IContentProvider#call
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.v.a(Unknown Source:55)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.q.h(:10)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.n.a(:11)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.n$c.onUidActive(:2)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at android.app.IUidObserver$Stub.onTransact(IUidObserver.java:155)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.c.onTransact(Unknown Source:0)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at android.os.Binder.execTransactInternal(Binder.java:1126)
02-21 11:52:46.069 16090 16103 E ShizukuServerV3: 	at android.os.Binder.execTransact(Binder.java:1090)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: failed send binder to user app rikka.appops in user 0
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: java.lang.NoSuchMethodError: android.content.IContentProvider#call
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.v.a(Unknown Source:55)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.h(:10)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.g(Unknown Source:41)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.d(:1)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.m.run(Unknown Source:2)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at android.os.Handler.handleCallback(Handler.java:907)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at android.os.Looper.loop(Looper.java:216)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.e(:2)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.Starter.main(:7)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-21 11:52:46.069 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
02-21 11:52:46.077 16090 16090 E ShizukuServerV3: provider is null cn.wq.myandroidtools.shizuku 0
02-21 11:52:46.106 16090 16103 D ShizukuServerV3: onProcessDied: pid=14079, uid=10064
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: failed send binder to user app com.catchingnow.icebox in user 0
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: java.lang.NoSuchMethodError: android.content.IContentProvider#call
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.v.a(Unknown Source:55)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.h(:10)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.g(Unknown Source:41)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.d(:1)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.m.run(Unknown Source:2)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at android.os.Handler.handleCallback(Handler.java:907)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at android.os.Looper.loop(Looper.java:216)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.e(:2)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.Starter.main(:7)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-21 11:52:46.403 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
02-21 11:52:46.469 16090 16103 D ShizukuServerV3: onUidActive: uid=10222
02-21 11:52:46.470 16090 16103 D ShizukuServerV3: onActive: uid=10222, packages=moe.shizuku.privileged.api
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: failed send binder to user app moe.shizuku.privileged.api in user 0
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: java.lang.NoSuchMethodError: android.content.IContentProvider#call
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.v.a(Unknown Source:55)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.q.h(:10)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.n.a(:9)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.n$c.onUidActive(:2)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at android.app.IUidObserver$Stub.onTransact(IUidObserver.java:155)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at moe.shizuku.server.c.onTransact(Unknown Source:0)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at android.os.Binder.execTransactInternal(Binder.java:1126)
02-21 11:52:46.509 16090 16103 E ShizukuServerV3: 	at android.os.Binder.execTransact(Binder.java:1090)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: failed send binder to user app moe.shizuku.privileged.api in user 0
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: java.lang.NoSuchMethodError: android.content.IContentProvider#call
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.v.a(Unknown Source:55)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.h(:10)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.d(:3)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.m.run(Unknown Source:2)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at android.os.Handler.handleCallback(Handler.java:907)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at android.os.Looper.loop(Looper.java:216)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.q.e(:2)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at moe.shizuku.server.Starter.main(:7)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-21 11:52:46.509 16090 16090 E ShizukuServerV3: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:396)
02-21 11:52:46.526 16090 16103 D ShizukuServerV3: onProcessDied: pid=15365, uid=1110133
02-21 11:52:46.526 16090 16103 D ShizukuServerV3: onProcessDied: pid=15094, uid=1110115
02-21 11:52:46.546 16090 16247 D ShizukuServerV3: onProcessDied: pid=12643, uid=1110120
02-21 11:52:47.254 16090 16247 D ShizukuServerV3: onProcessDied: pid=12398, uid=10173
02-21 11:52:47.280 16090 16247 D ShizukuServerV3: onProcessDied: pid=15479, uid=10148
--- shizuku end ---
info: shizuku_starter exit with 0

```

**Comment by RikkaW** [comment]
Please try v3.6.0

**Comment by 4ft35t** [comment]
系统已回滚，暂时无法测试 XD
