### ISSUE TITLE
Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by adithyan-hermit** [RikkaApps/Shizuku#638]
Please report bugs of Shizuku itself.

**Requirements:**

- [ ] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: adb
- Android version: 14
- Device: cmf by nothing

**Logs:**

Starting with wireless adb...

javax.net.ssl.SSLProtocolException: Read error: ssl=0xb4000071713852d8: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:592 0xb4000072113dbe20:0x00000003)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:570)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1088)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1072)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:869)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:740)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:705)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
	at java.io.DataInputStream.readFully(DataInputStream.java:203)
	at rikka.shizuku.z2.e(SourceFile:22)
	at rikka.shizuku.z2.a(SourceFile:195)
	at moe.shizuku.manager.starter.b$a.l(SourceFile:42)
	at rikka.shizuku.t9.n(SourceFile:12)
	at rikka.shizuku.kk.run(SourceFile:119)
	at rikka.shizuku.hz.run(SourceFile:13)
	at rikka.shizuku.om0.run(SourceFile:3)
	at rikka.shizuku.kg.l(SourceFile:1)
	at rikka.shizuku.kg$c.d(SourceFile:15)
	at rikka.shizuku.kg$c.n(SourceFile:29)
	at rikka.shizuku.kg$c.run(Unknown Source:0)

**Comment by molny** [comment]
+1 same issue

**Comment by Albert-coder46** [comment]
### _**
**_//////

**Comment by vvb2060** [comment]
Pair first

**Comment by zacharee** [comment]
I'm running into this in an Android 11 emulator, even after pairing multiple times. Pairing with a code succeeds and shows `shizuku` in the list of paired devices, but when I try to start Shizuku, I get this error, and the paired device disappears.

**Comment by Adriansyah-sketch** [comment]
[x]

**Comment by weirdal3333** [comment]
I am still intermittently running into this issue. Usually after a full reboot of the phone. I think it's a Google design choice...

**Comment by samueldossantospacifico6889-ctrl** [comment]
42613

**Comment by phatai19062012-svg** [comment]
how

**Comment by cesarjulio4519-byte** [comment]
On june 17
