### ISSUE TITLE
Can't start server after system update

### ISSUE THREAD

**Issue by sionescu** [RikkaApps/Shizuku#86]
On a Samsung S10+, after updating to patch G975FXXS9DTI8, I get this error:

```
$ adb shell sh /data/user_de/0/moe.shizuku.privileged.api/start.sh
info: start.sh begin
info: starter is /data/user_de/0/moe.shizuku.privileged.api/starter-v10
info: server dex path is /data/user_de/0/moe.shizuku.privileged.api/server-v10.dex
info: starter dex path is /data/user_de/0/moe.shizuku.privileged.api/starter-v10.dex
info: server dex path is /data/local/tmp/shizuku/server-v10.dex
info: starter dex path is /data/local/tmp/shizuku/starter-v10.dex
info: starter begin
info: killing old process...
info: starting server...
info: process forked, pid=31234
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '10-14 17:48:44.000' -d
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '10-14 17:48:44.000' -d -s ShizukuServer ShizukuManager
10-14 17:48:45.749 31235 31235 I ShizukuServer: starting server...
10-14 17:48:46.151 31235 31235 I ShizukuServer: send binder to user app rikka.appops in user 0
10-14 17:48:46.152 31235 31247 I ShizukuServer: send binder to user app rikka.appops in user 0
10-14 17:48:46.402 31235 31247 I ShizukuServer: send binder to user app moe.shizuku.privileged.api in user 0
10-14 17:48:46.405 31235 31235 I ShizukuServer: send binder to user app moe.shizuku.privileged.api in user 0
10-14 17:48:46.412 31235 31235 E ShizukuServer: provider is null moe.shizuku.privileged.api.shizuku 11
10-14 17:48:46.414 31235 31235 E ShizukuServer: failed send binder to user app moe.shizuku.privileged.api in user 150
10-14 17:48:46.414 31235 31235 E ShizukuServer: java.lang.SecurityException: Shell does not have permission to access user 150
10-14 17:48:46.414 31235 31235 E ShizukuServer:  android.app.IActivityManager$Stub.onTransact:3889 com.android.server.am.ActivityManagerService.onTransact:3427 android.os.Binder.execTransactInternal:1056 
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Parcel.createException(Parcel.java:2088)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Parcel.readException(Parcel.java:2056)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Parcel.readException(Parcel.java:2004)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.app.IActivityManager$Stub$Proxy.getContentProviderExternal(IActivityManager.java:8226)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at moe.shizuku.server.d0.n(ShizukuService.java:4)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at moe.shizuku.server.u.run(lambda:5)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Handler.handleCallback(Handler.java:883)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Looper.loop(Looper.java:237)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at moe.shizuku.server.Starter.main(Starter.java:14)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342)
10-14 17:48:46.414 31235 31235 E ShizukuServer: Caused by: android.os.RemoteException: Remote stack trace:
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at com.android.server.am.ActivityManagerService.getContentProviderExternal(ActivityManagerService.java:9072)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3889)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3427)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 	at android.os.Binder.execTransact(Binder.java:1029)
10-14 17:48:46.414 31235 31235 E ShizukuServer: 
--- shizuku end ---
info: shizuku_starter exit with 0
```

**Comment by RikkaW** [comment]
It seems that user 150 is a special "secure" user added by Samsung, adb cannot interact with apps inside. Nothing can do.
